src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdresseRepository::class)
 */
class Adresse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $detail_rue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDetailRue(): ?string
    {
        return $this->detail_rue;
    }

    public function setDetailRue(string $detail_rue): self
    {
        $this->detail_rue = $detail_rue;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/AdresseType.php
<?php

namespace App\Form;

use App\Entity\Adresse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdresseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('detail_rue',TextType:: class,[
                'label' =>  'numéro et nom de rue'

            ])
            ->add('code_postal',TextareaType::class)
            ->add('ville')
            ->add('pays')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Adresse::class,
        ]);
    }
}

src/Controller/AdresseController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Form\AdresseType;
use App\Repository\AdresseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/adresse')]
class AdresseController extends AbstractController
{
    #[Route('/', name: 'adresse_index', methods: ['GET'])]
    public function index(AdresseRepository $adresseRepository): Response
    {
        return $this->render('adresse/index.html.twig', [
            'adresses' => $adresseRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'adresse_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $adresse = new Adresse();
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($adresse);
            $entityManager->flush();

            return $this->redirectToRoute('adresse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adresse/new.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'adresse_show', methods: ['GET'])]
    public function show(Adresse $adresse): Response
    {
        return $this->render('adresse/show.html.twig', [
            'adresse' => $adresse,
        ]);
    }

    #[Route('/{id}/edit', name: 'adresse_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Adresse $adresse): Response
    {
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('adresse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adresse/edit.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'adresse_delete', methods: ['POST'])]
    public function delete(Request $request, Adresse $adresse): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adresse->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($adresse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('adresse_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/adresse/_delete_form.html.twig
<form method="post" action="{{ path('adresse_delete', {'id': adresse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adresse.id) }}">
    <button class="btn">Delete</button>
</form>

templates/adresse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Adresse{% endblock %}

{% block body %}
    <h1>Edit Adresse</h1>

    {{ include('adresse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('adresse_index') }}">back to list</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}

templates/adresse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse index{% endblock %}

{% block body %}
    <h1>Adresse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Detail_rue</th>
                <th>Code_postal</th>
                <th>Ville</th>
                <th>Pays</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for adresse in adresses %}
            <tr>
                <td>{{ adresse.id }}</td>
                <td>{{ adresse.detailRue }}</td>
                <td>{{ adresse.codePostal }}</td>
                <td>{{ adresse.ville }}</td>
                <td>{{ adresse.pays }}</td>
                <td>
                    <a href="{{ path('adresse_show', {'id': adresse.id}) }}">show</a>
                    <a href="{{ path('adresse_edit', {'id': adresse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('adresse_new') }}">Create new</a>
{% endblock %}

templates/adresse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adresse{% endblock %}

{% block body %}
    <h1>Create new Adresse</h1>

    {{ include('adresse/_form.html.twig') }}

    <a href="{{ path('adresse_index') }}">back to list</a>
{% endblock %}

templates/adresse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse{% endblock %}

{% block body %}
    <h1>Adresse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adresse.id }}</td>
            </tr>
            <tr>
                <th>Detail_rue</th>
                <td>{{ adresse.detailRue }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ adresse.codePostal }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ adresse.ville }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ adresse.pays }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('adresse_index') }}">back to list</a>

    <a href="{{ path('adresse_edit', {'id': adresse.id}) }}">edit</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}